### ISSUE TITLE
Binder: Could not find a kernel matching Scala

### ISSUE THREAD

**Issue by edwardcwang** [freechipsproject/chisel-bootcamp#100]
Lately I've been seeing this error when using the bootcamp on binder with the error: "Could not find a kernel matching Scala. Please select a kernel" with the only option being "Python 3". Did binder change its kernel options/settings recently?

**Comment by chick** [comment]
I am also getting this error. Not sure what has changed

**Comment by edwardcwang** [comment]
Fixed by #101
