### ISSUE TITLE
Local install for bootcamp into Windoze 10 reporting errors?

### ISSUE THREAD

**Issue by Bazmundi** [freechipsproject/chisel-bootcamp#117]
Running Java 8 as build 1.8.0_261-b12 on Windoze 10.

As per [instructions](https://github.com/freechipsproject/chisel-bootcamp/blob/master/Install.md) for windoze 10.

Downloaded [coursier](https://git.io/vgvpD).

Ran the following in cmd prompt (as per [instructions](https://github.com/freechipsproject/chisel-bootcamp/blob/master/Install.md) with coursier in directory "C:\Users\pierc\dev\jupyter\jupyter-scala"):

### cmd1
```
C:\Users\pierc\dev\jupyter\jupyter-scala>java -noverify -jar coursier launch -r jitpack -i user -I user:sh.almond:scala-kernel-api_2.12.8:0.2.1 sh.almond:scala-kernel_2.12.8:0.2.1 --sources --default=true -- --install
```

Got the following:

```
[2KDownloaded 1 missing file(s) / 1
[1A[2KUnrecognized argument: --sources
Unrecognized argument: --default=true
```

I removed "--sources --default=true" from command line in cmd shell to run:

### cmd2
```
java -noverify -jar coursier launch -r jitpack -i user -I user:sh.almond:scala-kernel-api_2.12.8:0.2.1 sh.almond:scala-kernel_2.12.8:0.2.1  -- --install   
```

That previous line appeared to run.

Problematic is I found scala folder "C:\Users\pierc\AppData\Roaming\jupyter\kernels" where you would expect it.  But its empty?

Certainly, when I ran jupyter lab it found no scala kernel.

When I try running the **cmd2** again it obviously reports scala already installed. 

So I use the --force option as the script suggests and ran:

### cmd3
```
java -noverify -jar coursier launch -r jitpack -i user -I user:sh.almond:scala-kernel-api_2.12.8:0.2.1 sh.almond:scala-kernel_2.12.8:0.2.1  -- --force --install   
```

The command above removes the empty scala folder from the AppData path, but it drops out with:

```
Error: C:\Users\pierc\AppData\Roaming\jupyter\kernels\scala
```

This happens each time I ran **cmd3**, so I ran **cmd2** again which results in an error:

```
Error: Illegal char <:> at index 2: /C:/Users/pierc/dev/jupyter/jupyter-scala/coursier
```

This suggests either the coursier file gets corrupted during the run or a conditional section that is activated during this sequence has a bug in it.

So, I downloaded coursier again but still got the problem of the illegal char.  So it appears the install process is now completely broken some how.

So:

1. Install does not work using suggested **cmd1** for Windoze .
2. Inaugural run of **cmd2** only creates an empty scala directory under kernels.
3. The **cmd2** script correctly reports scala "exists" if ran again (because it finds the empty directory).
4. Using --force option (**cmd3**) happily deletes the empty directory but then raises error reporting the scala kernal directory path (whatever that is supposed to mean).
5. Subsequently running the command **cmd2** results in a error suggesting corruption of the coursier file, or at least a conditional section is run that has a bug in it on first inspection, but running against a fresh download of the coursier file sees the same problem.

Not sure then whether I have caused a problem because I dropped the --sources and --default parameters or the script is simply just broken.  

Something somewhere may have been touched, that has to be untouched, to get around the illegal character problem?

The idea that you may need to adjust the script is great, if it was intuitive and did not break any re-install attempts.

So, I need first a hint to back out of the scala almond install please.

Then we can work our way back into why the command line does not work as described.

**Comment by edwardcwang** [comment]
Hey, thanks for your interest in Chisel and reporting this! I did some experiments just now, and indeed, what happened is that almond/coursier updated their interface and broke a bunch of things :(

I just pushed a fix to the Windows installation instructions and test them just now, and they seem to work. Please take a look and let me know if it works for you!

Note: at one point when (re-)installing the Scala kernel, you may need to append a `--force` at the end of the command.

**Comment by Bazmundi** [comment]
Brilliant! Thanks.
