### ISSUE TITLE
java.io.IOException: Cannot run program "cp": CreateProcess error=2

### ISSUE THREAD

**Issue by jiarui-tw** [freechipsproject/chisel-bootcamp#127]
Hello,

Anybody can help me please?

I'm studying Chisel and trying chisel-bootcamp locally with Jupyter under Windows 10. I used Java 8 from Oracle download and OpenJDK8U-jdk_x64_windows_openj9_8u275b01_openj9-0.23.0.msi and follow the steps instructed here.

But, I still meet the attached issue when I run Moving Average Filter.

I also tried with OpenJDK8U-jdk_x64_windows_hotspot_8u275b01.msi and install Grapviz installation by using both of pip command and graphviz-install-2.44.1-win64.exe. And also run coursier. But, the attached issues can't be solved. 

Thank you very much for you help.

<img width="734" alt="java-version" src="https://user-images.githubusercontent.com/23741830/104798099-df06b300-57fe-11eb-9f95-b3b3c26465ba.png">
<img width="960" alt="Failed in running of Moving Average3" src="https://user-images.githubusercontent.com/23741830/104798131-183f2300-57ff-11eb-8287-5b784748d0cb.png">

.<img width="485" alt="Environment Parameters" src="https://user-images.githubusercontent.com/23741830/104809313-5bad8780-5827-11eb-99e4-64071ec054f9.png">
<img width="484" alt="System Parameters" src="https://user-images.githubusercontent.com/23741830/104809333-81d32780-5827-11eb-97f1-816a8ca7dcbe.png">

Best regards,
Ray Huang

**Comment by edwardcwang** [comment]
Hi Ray, thanks for your interest in Chisel, and thank you for trying out the Chisel bootcamp! I'm taking a look at this to see what is going on.

**Comment by edwardcwang** [comment]
@jiarui-tw Just pushed a fix for this that removes the hardcoded 'cp' so it should be more platform independent now. Does it work for you if you pull and try again? (make sure to restart the kernel)
