### ISSUE TITLE
rocket-dsp-utils-assembly-1.0.jar not found

### ISSUE THREAD

**Issue by poweihuang17** [freechipsproject/chisel-bootcamp#16]
Hi, sorry, it's me again.
When I'm working on section Setup of 2.5, it throws:
java.nio.file.NoSuchFileException: /Users/Powei/Dropbox/riscv/rocket-dsp-utils-assembly-1.0.jar
  sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
  sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
  sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
  sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
  sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
  java.nio.file.Files.readAttributes(Files.java:1737)
  ammonite.ops.stat$full$.apply(Model.scala:69)
  ammonite.ops.package$.fileData(package.scala:105)
  ammonite.runtime.SpecialClassLoader.jarSignature(ClassLoaders.scala:155)
  ammonite.runtime.SpecialClassLoader.add(ClassLoaders.scala:141)
  ammonite.runtime.Frame$$anonfun$addClasspath$2.apply(ClassLoaders.scala:35)
  ammonite.runtime.Frame$$anonfun$addClasspath$2.apply(ClassLoaders.scala:35)
  scala.collection.immutable.List.foreach(List.scala:392)
  ammonite.runtime.Frame.addClasspath(ClassLoaders.scala:35)
  ammonite.interp.Interpreter.handleEvalClasspath(Interpreter.scala:671)
  ammonite.interp.Interpreter$$anon$2$$anon$1.handleClasspath(Interpreter.scala:697)
  ammonite.interp.Interpreter$DefaultLoadJar.doHandleClasspath(Interpreter.scala:838)
  ammonite.interp.Interpreter$DefaultLoadJar.cp(Interpreter.scala:845)
  $sess.cmd17Wrapper$Helper.<init>(cmd17.sc:2)
  $sess.cmd17Wrapper.<init>(cmd17.sc:329)
  $sess.cmd17$.<init>(cmd17.sc:258)
  $sess.cmd17$.<clinit>(cmd17.sc:-1)

**Comment by poweihuang17** [comment]
I believe I had follow the section "Local Installation - Mac/Linux" in Readme.

**Comment by poweihuang17** [comment]
I found this: "We have compiled the necessary depedencies, which are not all published on Maven, into a jar file. Contact the contributors if you want a copy. If you are not at the bootcamp, you can safely skip this section.".  So, could I just skip the section IPXACT example and proceed on section "FIR Filter Generator"?

**Comment by grebe** [comment]
For now, you should skip this section. It was put together for a tutorial where we had more control over the installation and had some hand assembled jar that included some functionality from rocket-chip. It is an ongoing effort to make rocket-chip and rocket-dsp-utils more easily usable as a library.

Let's leave this issue open as a reminder to clean this up.

See also grebe/rocket-chip#1

**Comment by poweihuang17** [comment]
@grebe OK.I'll skip to part3. Thanks. Overall, it's a really good tutorial for chisel. Thanks for the effort.
