### ISSUE TITLE
can not run 2.1 locally

### ISSUE THREAD

**Issue by yberlin** [freechipsproject/chisel-bootcamp#167]
I clone the repo and install like readme. In Ubuntu system
but I got error running cell 2.1
cmd0.sc:2: object ops is not a member of package ammonite
val res0_1 = interp.load.module(ammonite.ops.Path(java.nio.file.FileSystems.getDefault().getPath(path)))
                                         ^Compilation Failed

Compilation Failed

**Comment by ParthPant** [comment]
+1 getting the same error.
Did you find a way to fix this?

**Comment by yberlin** [comment]
> Sorry it has been a long time, I forgot if I fix this. 
But a quick way to start a chisel project is that you can find another complete project and run~

**Comment by yebosirius** [comment]
+1 get the same error.
I have found the solution for days (smile cry)

**Comment by NOS-AE** [comment]
> I clone the repo and install like readme. In Ubuntu system but I got error running cell 2.1 cmd0.sc:2: object ops is not a member of package ammonite val res0_1 = interp.load.module(ammonite.ops.Path(java.nio.file.FileSystems.getDefault().getPath(path))) ^Compilation Failed
> 
> Compilation Failed

have you selected the kernel: scala?

**Comment by HahaLan97** [comment]
Is there any solution for this yet? I'm stuck here as well.

**Comment by HahaLan97** [comment]
Magic happens when I restarted the notebook. lol

**Comment by Frwere** [comment]
It could be a problem related to your almond version.
make sure you follow strictly the "Jupyter Backend for Scala" part in the installation readme file, copy the commands into your terminal and run,
and you'll find it functions well
