### ISSUE TITLE
jupyter-scala installation problem

### ISSUE THREAD

**Issue by jeehoonkang** [freechipsproject/chisel-bootcamp#44]
https://github.com/freechipsproject/chisel-bootcamp#local-installation---maclinux

`cd jupyter-scala && ./jupyter-scala` doesn't work:

```zsh
% cd jupyter-scala && ./jupyter-scala
zsh: no such file or directory: ./jupyter-scala
```

Probably because `alexarchambault/jupyter-scala` repo is moved to `almond-sh/almond` and changed a lot.

**Comment by edwardcwang** [comment]
This will be fixed by #43
