### ISSUE TITLE
Investigate JupyterHub

### ISSUE THREAD

**Issue by grebe** [freechipsproject/chisel-bootcamp#46]
[This](https://github.com/jupyterhub/jupyterhub) seems ideal for our use-case. There's a kubernetes [thing](https://github.com/jupyterhub/kubespawner) that seems useful too.

**Comment by jackkoenig** [comment]
Related issue https://github.com/jupyterhub/binder/issues/125

**Comment by grebe** [comment]
Binder seems to have resolved many of our use-cases
