### ISSUE TITLE
Compilation error in cell 12 of 1_intro_to_scala

### ISSUE THREAD

**Issue by lomax** [freechipsproject/chisel-bootcamp#49]
I'm getting an error trying to run code in the cell number 12 in the notebook:
```
val randomList = List(util.Random.nextInt(), util.Random.nextInt(), util.Random.nextInt(), util.Random.nextInt())
var listSum = 0
for (value <- randomList) {
  listSum += value
}
println("sum is " + listSum)
```
error is:
`cmd17.sc:1: object Random is not a member of package ammonite.util
val randomList = List(util.Random.nextInt(), util.Random.nextInt(), util.Random.nextInt(), util.Random.nextInt())
                           ^cmd17.sc:1: object Random is not a member of package ammonite.util
val randomList = List(util.Random.nextInt(), util.Random.nextInt(), util.Random.nextInt(), util.Random.nextInt())
                                                  ^cmd17.sc:1: object Random is not a member of package ammonite.util
val randomList = List(util.Random.nextInt(), util.Random.nextInt(), util.Random.nextInt(), util.Random.nextInt())
                                                                         ^cmd17.sc:1: object Random is not a member of package ammonite.util
val randomList = List(util.Random.nextInt(), util.Random.nextInt(), util.Random.nextInt(), util.Random.nextInt())
                                                                                                ^Compilation Failed
Compilation Failed`

According to the Coursier log i should have
`https://repo1.maven.org/maven2/com/lihaoyi/ammonite-util_2.11/1.2.1-12-bc459e3/ammonite-util_2.11-1.2.1-12-bc459e3.pom
  100,0% [##########] 1,9 KiB (11,0 KiB / s)`
installed as a dependency for almond.

**Comment by lomax** [comment]
And after i added import scala.util once in this cell the issue dissapeared.
So by default it were looking for util.Random inside ammonite package and after i executed import scala.util just once it start to search inside the standard scala library.

**Comment by grebe** [comment]
Thanks for pointing this out!
