### ISSUE TITLE
Make notebooks proxy aware

### ISSUE THREAD

**Issue by lomax** [freechipsproject/chisel-bootcamp#50]
To execute the first cell of 2.1_first_module inside the environment behind the proxy i have tomake ammonite shell proxy aware and found this solution:
```scala
System.setProperty("https.proxyHost","proxy.example.com")
System.setProperty("https.proxyPort","3128")
```
^---- should be added before importing chisel packages
I haven't tried running the jupyter itself with JAVA_OPTS="-Dhttps.proxyHost=proxy.example.com -Dhttps.proxyPort=3128"

**Comment by grebe** [comment]
Does the solution look OK to you?

**Comment by lomax** [comment]
> Does the PR look OK to you?

Yeah, that is exactly what I did to fix it locally.
