### ISSUE TITLE
cannot find default main class when execute" ./almond install "

### ISSUE THREAD

**Issue by botaichang** [freechipsproject/chisel-bootcamp#72]
when i execute 
```bash
./almond install 
```
returns 
```
Cannot find default main class. Specify one with -M or --main.
```
could anyone tell me what the main class for almond ?

**Comment by grebe** [comment]
I'm not sure why you see this b/c I haven't seen this before. Are you sure coursier completed the downloads succesfully?

I think the main class is [`almond.echo.EchoKernel`](https://github.com/almond-sh/almond/blob/ac8c4248fe1a38961a49697ee1abe87c38c2603d/modules/echo/src/main/scala/almond/echo/EchoKernel.scala#L10), but I'm not positive.

**Comment by botaichang** [comment]
> I'm not sure why you see this b/c I haven't seen this before. Are you sure coursier completed the downloads succesfully?
> 
> I think the main class is [`almond.echo.EchoKernel`](https://github.com/almond-sh/almond/blob/ac8c4248fe1a38961a49697ee1abe87c38c2603d/modules/echo/src/main/scala/almond/echo/EchoKernel.scala#L10), but I'm not positive.

@grebe thanks very much grebe. I download libraries again and finally install scala kernel successfully. Thank you much. It's very kind of you .
