### ISSUE TITLE
Links to Cheatsheet and API are broken

### ISSUE THREAD

**Issue by vidhatre** [freechipsproject/chisel-bootcamp#81]
While doing the bootcamp when i tried to access the links provided in the notebook, they did not resolve. I assume there was an update on where the cheatsheet and API is now. 

Bootcamp module: 2.2_comb_logic
Links broken:
- 'Chisel Cheatsheet' -> https://chisel.eecs.berkeley.edu/documentation.html
- 'Chisel API' -> https://chisel.eecs.berkeley.edu/api/#package

I was able to find the API documentation at https://www.chisel-lang.org/api/latest/
I was not able to find the cheatsheet.

**Comment by seldridge** [comment]
Thanks for reporting this. I can get a PR together. In the mean time, you can get the latest version of the cheatsheet here: https://github.com/freechipsproject/chisel-cheatsheet/releases/download/190905/chisel_cheatsheet.pdf
